### PR TITLE
Fix crash with OptiFine

### LINKED ISSUE #79: Crash on world load with optifine
As the title says.. and when I am loading the world it takes so long too for some reason... I am only using optifine with primal winter :/
this is what the crash says: "The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: Index 15 out of bounds for length 7."
I am on the last version 1.20.1 .

### PR DESCRIPTION
**Pull request by KaiAF**
When loading Primal Winter with OptiFine into a world, it would cause a "ArrayIndexOutOfBoundsException". This is because you are modifying all constants that equaled "5" in the renderSnowAndRain method: `@ModifyConstant(method = "renderSnowAndRain", constant = {@Constant(intValue = 5), @Constant(intValue = 10)})`

In vanilla, this works fine. In OptiFine, it requires to reflect a Forge method.

When the mixin is trying to apply with OptiFine, it looks like this (not sure why it converts to an Object array): 
```java
        if (Reflector.IForgeDimensionSpecialEffects_renderSnowAndRain.exists()) {
            DimensionSpecialEffects var10000 = this.f_109465_.m_104583_();
            ReflectorMethod var10001 = Reflector.IForgeDimensionSpecialEffects_renderSnowAndRain;
            Object[] var10002 = new Object[]{this.f_109465_, this.f_109477_, partialTicks, lightmapIn, xIn, null, null};
            var10002[this.constant$zze000$modifySnowAmount(5)] = yIn;
            var10002[6] = zIn;
            if (Reflector.callBoolean(var10000, var10001, var10002)) {
                return;
            }
        }
```

So, I created a MixinPlugin which will now apply an ordinal if OptiFine is found `@ModifyConstant(method = "renderSnowAndRain", constant = {@Constant(intValue = 5, ordinal = 1), @Constant(intValue = 10)})`

Fixes #79.

### CODE REVIEW

**Comment by alcatrazEscapee** [comment]
Thank you for diagnosing the issue. The correct solution would be to narrow the mixin target so it doesn't conflict, because this PR as is is unsustainable. I _do not_ want explicit support for optifine, because it's a closed source, ancient piece of garbage, duplicating the entire mixin with a config plugin is the worst possible solution, along with no future indication of maintainability because I do not, and will not, use nor test with optifine on principle. It also appears to be missing an implementation on Forge - or at least any documentation onto where the mixin plugin gets discovered.

**Comment by KaiAF** [comment]
@alcatrazEscapee I have cleaned up the code to only modify the one mixin. I have tested without OptiFine and with it and it works normally. I have documented the change with comments to explain why it's different. Other than the gradle files that were changed so that it could compile, only one file is changed.

I understand that you do not like OptiFine and that this is your mod, which is why it's not required for you to fix this crash. I only wanted to fix it as I have received reports of it in the OptiFine discord. Just know that this error can't be fixed on OptiFine's side, it requires to add the reflector for Forge support.

**Comment by FlakeUchih** [comment]
How do i go about applying this fix?

**Comment by FlakeUchih** [comment]
Could i get the patched mod file please?

**Comment by seacheese1108** [comment]
> When loading Primal Winter with OptiFine into a world, it would cause a "ArrayIndexOutOfBoundsException". This is because you are modifying all constants that equaled "5" in the renderSnowAndRain method: `@ModifyConstant(method = "renderSnowAndRain", constant = {@Constant(intValue = 5), @Constant(intValue = 10)})`
> 
> In vanilla, this works fine. In OptiFine, it requires to reflect a Forge method.
> 
> When the mixin is trying to apply with OptiFine, it looks like this (not sure why it converts to an Object array):
> 
> ```java
>         if (Reflector.IForgeDimensionSpecialEffects_renderSnowAndRain.exists()) {
>             DimensionSpecialEffects var10000 = this.f_109465_.m_104583_();
>             ReflectorMethod var10001 = Reflector.IForgeDimensionSpecialEffects_renderSnowAndRain;
>             Object[] var10002 = new Object[]{this.f_109465_, this.f_109477_, partialTicks, lightmapIn, xIn, null, null};
>             var10002[this.constant$zze000$modifySnowAmount(5)] = yIn;
>             var10002[6] = zIn;
>             if (Reflector.callBoolean(var10000, var10001, var10002)) {
>                 return;
>             }
>         }
> ```
> 
> So, I created a MixinPlugin which will now apply an ordinal if OptiFine is found `@ModifyConstant(method = "renderSnowAndRain", constant = {@Constant(intValue = 5, ordinal = 1), @Constant(intValue = 10)})`
> 
> Fixes #79.

how do i go about doing this?

**Comment by alcatrazEscapee** [comment]
7d1b8a9dc63feb9cf8abc3c0d53949b2b9458087

**Pull request closed without merging**
